#!/bin/bash
# Render monitored phone extensions for GNU screen hardstatus line
#
#  Copyright (C) 2014  LoVullo Associates, Inc.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# For each extension, a box is rendered (green for available, otherwise
# yellow) indicating, essentially, whether they are away from their desk or
# not (or do not want to be disturbed).
#
# Great for stalking and for productivity.
# #

data=$( cat "$( dirname $0 )/extlist" )
path=~/gitrepos/lovlib/tools/lovullo

# status colors (CHM is 1-based); second row is watch colors
colors=(  '' 'g' 'y' 'y' 'y' 'y' \
          '' 'g' 'm' 'm' 'm' 'm' \
)

# load monitor data
monfile=/tmp/.extmon
monitor="$( cat "$monfile" )"

chm-ind()
{
  chm=$( cat - )
  chr=$1

  color=${colors[$chm]}

  # output the given chr with the appropriate status color
  echo -en "\005{+ ${color}W}$chr\005{-}"
}

IFS=$'\n'
for line in $data; do
  ext=$( cut -d' ' -f1 <<< "$line" )
  chr=$( cut -d' ' -f2 <<< "$line" )

  # check for spacer
  if [ "$ext" == '-' ]; then
    echo -n ' '
    continue
  fi

  # get CHM for the extension
  status="$( $path/phonectl --ext $ext --get chm )"

  # if monitoring, then double status
  grep -qF "$ext" <<< "$monitor" \
    && status=$((status*2))

  # display status
  chm-ind $chr <<< "$status"

  # are we monitoring this extension?
  if [ $status -eq 1 ]; then
    grep -qF "$ext" <<< "$monitor" \
      && {
        # notify and remove from the monitor file
        beep -f 1700 -l 200 -r 2 -d 200 \
          && sed -i "/^$ext$/d" "$monfile"
      }
  fi
done

echo
